#!/bin/sh /etc/rc.common
# LuCI-app-bras
# MIT license | Chunyang Xu <http://xuchunyang.me>

# FIXME:
# 1) Clean debug message (only keey necessary) 2)
# 2) Try to keep all Condition statement with same style

. /etc/functions.sh

START=60
STOP=01

xl2tpd_run_dir=/var/run/xl2tpd

xl2tpd_config_file=/etc/xl2tpd/bras.xl2tpd.conf
ppp_option_file=/etc/ppp/options.bras.xl2tpd
ppp_secret_file=/etc/ppp/chap-secrets

# default point-to-point interface created by l2tp
PPP=ppp1

# Create l2tp configuration files according user/name from web UI
create_bras_conf() {
    logger -t "bras" "starting configurate xl2tpd"

    if ! [ -f /etc/ppp/options.bras.xl2tpd ]; then
        logger -s -t "bras" "Error, $ppp_option_file not found!"
        exit 255
    fi

    config_get username $1 username
    config_get password $1 password

    sed -e "s#|USERNAME|#$username#g" \
        /etc/xl2tpd/xl2tpd.conf.template > $xl2tpd_config_file

    sed -e "s#|USERNAME|#$username#g" \
        -e "s#|PASSWORD|#$password#g" \
        /etc/ppp/chap-secrets.template > $ppp_secret_file

    logger -t "bras" "configurate xl2tpd done"

}

# 在 pppd 不改变路由的情况下 #TODO: 总是这样吗？ 路由表的更新到底受到到哪些因素影响？
update_route_table() {
    logger -t "bras"  "Updating route table"
    # FIXME: how to keep variable outside shell script?
    orig_gateway=`cat /tmp/ORIG_GATEWAY`

    # Add bras route first
    route add -net 58.192.112.38 netmask 255.255.255.255 gw $orig_gateway
    route add -net 58.192.112.39 netmask 255.255.255.255 gw $orig_gateway

    # Fix route after pppd
    if (route del -net default && route add -net default dev $PPP); then
        logger -t "bras" "add ${PPP} as default route done"
    else
        route add -net default gw $orig_gateway
        logger -s -t "bras" "Error! add ${PPP} failed! recover origin gateway done"
        exit 255
    fi

    # 最后，添加校内路由表
    /usr/bin/add-seu-route.sh $orig_gateway

    logger -t "bras" "updating route table done"
}

start()
{
    config_load bras
    config_foreach create_bras_conf

    # save orginal gateway
    # 获取成功连上 PPPoE 之后、拨 Bras 之前的网关
    orig_gateway=`route -e | grep default | sed 's/default *//g' | sed 's/  *.*//g'`
    echo $orig_gateway  > /tmp/ORIG_GATEWAY # Ugly! 保存初始网关

    logger -t "bras" "starting xl2tpd"
    [ -d $xl2tpd_run_dir ] || mkdir -p $xl2tpd_run_dir
    pidof xl2tpd || xl2tpd -c $xl2tpd_config_file
    sleep 1                     # FIXME not sure is it necessary?

    if pidof xl2tpd > /dev/null; then
        logger -t "bras" "xl2tpd is running!"
        echo 'c bras' > $xl2tpd_run_dir/l2tp-control
    else
        logger -s -t "bras" "Error: xl2tpd start failed"
        exit 255
    fi

    sleep 3
    # if ppp1 not found, use ppp0
    if ifconfig ppp2 &> /dev/null; then
        PPP=ppp2
    elif ifconfig ppp1 &> /dev/null; then
        PPP=ppp1
    elif ifconfig ppp9 &> /dev/null; then
        PPP=ppp0
    else
        logger -s -t "bras" "Error: no ppp interface found"
        exit 255
    fi

    # update default route and SEU route
    update_route_table

    # check final connection
    if ping -W1 -c1 baidu.com 2> /dev/null; then
        logger -t "bras"  "bras connection Succeed"
    fi
}

stop()
{
    logger -t "bras" "Killing xl2tpd"
    ps | grep -ie xl2tpd | grep -v grep | awk '{print $1}' | xargs kill -9
    orig_gateway=`cat /tmp/ORIG_GATEWAY`
    route add -net default gw $orig_gateway && logger -t "bras" "Recovering default route done"
}
