#!/bin/sh /etc/rc.common

. /etc/functions.sh

START=60
STOP=01

xl2tpd_run_dir=/var/run/xl2tpd

xl2tpd_config_file=/etc/xl2tpd/bras.xl2tpd.conf
ppp_option_file=/etc/ppp/options.bras.xl2tpd
ppp_secret_file=/etc/ppp/chap-secrets

bras_conf() {
    echo "starting config xl2tpd..."
    config_get username $1 username
    config_get password $1 password

    #Only for debug!
    echo $username
    echo $password

    sed -e "s#|USERNAME|#$username#g" \
        /etc/xl2tpd/xl2tpd.conf.template > $xl2tpd_config_file

    [ -f /etc/ppp/options.bras.xl2tpd ] || echo "Error, ppp-opt filecopied failed!"

    sed -e "s#|USERNAME|#$username#g" \
        -e "s#|PASSWORD|#$password#g" \
        /etc/ppp/chap-secrets.template > $ppp_secret_file

    echo "config xl2tpd complete!"

}

# 在 pppd 不改变路由的情况下 #TODO: 总是这样吗？ 路由表的更新到底收到那些因素影响？
update_route_table() {
    echo "updating route table..."
    # 获取拨号以前的的网关
    set $(route -e | grep default) # TODO:使用 awk 或 sed 更自然
    orig_gateway=$2

    # 首先，添加 bras.seu.edu.cn 到 非ppp0 的网络接口。bras.seu.edu.cn 有两
    # 个IP, 这里本应该添加分配的IP，xl2tpd -D 可以看到是哪个IP
    route add -net 58.192.112.38 netmask 255.255.255.255 gw $orig_gateway
    route add -net 58.192.112.39 netmask 255.255.255.255 gw $orig_gateway
    # 之后，才能修改改默认路由 (default route)
    route del -net default
    route add -net default dev ppp0 # 所有网路请求，默认使用 ppp0 口
    if [ $? == 0 ]; then
        touch /tmp/route_add_ppp0_done
    fi
    # 最后，添加校内路由表 # TODO: 以 bbs.seu.edu.cn 为例,需要补全
    route add -net 58.192.114.8 netmask 255.255.255.255 gw $orig_gateway
}

start()
{
    config_load bras
    config_foreach bras_conf bras

    echo "starting xl2tpd..."
    [ -d $xl2tpd_run_dir ] || mkdir -p $xl2tpd_run_dir
    xl2tpd -c $xl2tpd_config_file -D  &> /dev/null &

    sleep 1

    pgrep xl2tpd > /dev/null
    if [ $? == 0 ]; then
        echo 'c bras' > $xl2tpd_run_dir/l2tp-control
    else
        echo 'xl2tpd not running'
        exit 255
    fi

    sleep 4
    ifconfig ppp0 > /dev/null
    if [ $? != 0 ]; then
        update_route_table
    else
        echo "xl2tpd is running , but Bras start failed!"
        exit 255
    fi
    # TODO: 网络端口转发, iptable, /etc/firewall.user
}

stop()
{
    echo "stopping"
    pkill -9 xl2tpd
    #TODO: 恢复默认网关
}
