#!/bin/sh /etc/rc.common
# LuCI-app-Bras
# Maintainer: xcy <xuchunyang56@gmail.com>

. /etc/functions.sh

START=60
STOP=01

xl2tpd_run_dir=/var/run/xl2tpd

xl2tpd_config_file=/etc/xl2tpd/bras.xl2tpd.conf
ppp_option_file=/etc/ppp/options.bras.xl2tpd
ppp_secret_file=/etc/ppp/chap-secrets

create_bras_conf() {
    echo "starting config xl2tpd..."
    config_get username $1 username
    config_get password $1 password

    sed -e "s#|USERNAME|#$username#g" \
        /etc/xl2tpd/xl2tpd.conf.template > $xl2tpd_config_file

    sed -e "s#|USERNAME|#$username#g" \
        -e "s#|PASSWORD|#$password#g" \
        /etc/ppp/chap-secrets.template > $ppp_secret_file

    echo "config xl2tpd done!"
}

# 在 pppd 不改变路由的情况下 #TODO: 总是这样吗？ 路由表的更新到底受到到哪些因素影响？
update_route_table() {
    echo "updating route table..."

    # route BRAS(bras.seu.edu.cn) first
    orig_gateway=`cat /tmp/ORIG_GATEWAY`
    route add -net 58.192.112.38 netmask 255.255.255.255 gw $orig_gateway
    route add -net 58.192.112.39 netmask 255.255.255.255 gw $orig_gateway

    route add -net default dev $?
    if [ $? == 0 ]; then
        echo "add $? as default route done!"
    else
        route add -net default gw $orig_gateway && echo "recover original gateway done!"
        exit 255
    fi

    route add -net 58.192.114.8  netmask 255.255.255.255 gw $orig_gateway 2> /dev/null
    route add -net 10.0.0.0      netmask 255.0.0.0       gw $orig_gateway 2> /dev/null
    route add -net 58.192.112.0  netmask 255.255.240.0   gw $orig_gateway 2> /dev/null
    route add -net 58.192.112.39 netmask 255.255.255.255 gw $orig_gateway 2> /dev/null
    route add -net 121.229.0.0   netmask 255.255.0.0     gw $orig_gateway 2> /dev/null
    route add -net 121.248.48.0  netmask 255.255.240.0   gw $orig_gateway 2> /dev/null
    route add -net 202.119.24.55 netmask 255.255.255.255 gw $orig_gateway 2> /dev/null
    route add -net 211.65.32.0   netmask 255.255.224.0   gw $orig_gateway 2> /dev/null
    route add -net 211.65.232.0  netmask 255.255.252.0   gw $orig_gateway 2> /dev/null

    echo "update route table done!"
}

start()
{
    config_load bras
    config_foreach create_bras_conf

    orig_gateway=`route -e | grep default | sed 's/default *//g' | sed 's/  *.*//g'`
    echo $orig_gateway  > /tmp/ORIG_GATEWAY # save original gateway

    echo "starting xl2tpd..."
    [ -d $xl2tpd_run_dir ] || mkdir -p $xl2tpd_run_dir
    pidof xl2tpd || xl2tpd -c $xl2tpd_config_file
    sleep 1

    pgrep xl2tpd &> /dev/null
    if [ $? == 0 ]; then
        echo "xl2tpd is running!"
        echo 'c bras' > $xl2tpd_run_dir/l2tp-control
    else
        echo 'Error! xl2tpd not running!'
        exit 255
    fi

    sleep 3

    # xl2tpd's pppd interface may be ppp1 when your OpenWRT already has ppp interface(e.g pppoe-wan)
    ifconfig ppp0 &> /dev/null
    ppp0_status=$?
    if [ ppp0_status == 0 ]; then
        echo "ppp0 is running!"
        update_route_table ppp0
    else
        echo "ppp0 does not exist!"
    fi

    ifconfig ppp1 &> /dev/null
    ppp1_status=$?
    if [ ppp1_status == 0 ]; then
        echo "ppp1 is running!"
        return 1
        update_route_table ppp1
    else
        echo "ppp1 does not exist!"
    fi

    if [ ppp0_status == 0 ] || [ ppp1_status == 0 ]; then
        echo "Bras's ppp interface exit!"
    else
        kill -9 `pidof xl2tpd` && echo 'kill xl2tpd done'
    fi

}

stop()
{
    echo "killing xl2tpd..."
    kill -9 xl2tpd && echo "kill xl2tpd done"
    orig_gateway=`cat /tmp/ORIG_GATEWAY`
    route add -net default gw $orig_gateway && echo "Recovering default route done!"
}
